#!/bin/bash

usage()
{

    echo '
This script will change prefix for your classes.

Usage:
	prefixChange [--simple] <oldPrefix> <newPrefix> <directory>
'

    exit 0
}

main()
{
	set -eo pipefail

	if [ "$#" -lt 3 ]; then
		usage
		exit
	fi

	OLD_PREFIX="$1"
	NEW_PREFIX="$2"
	DIR="$3"

	echo "Renaming files..."
	find "$DIR" -regex ".*/${OLD_PREFIX}.*" -exec rename "s/${OLD_PREFIX}/${NEW_PREFIX}/g" {} \;
	echo "Changing file contents..."
	find -E "$DIR" -iregex '.*\.(h|m|mm|swift|pbxproj|storyboard)' -exec sed -i '' "s/${OLD_PREFIX}/${NEW_PREFIX}/g" {} \;
	echo "Done."
}

main "$@"
